
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestiontournees_qa
    username: postgres
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate