spring:
  application:
    name: Gestiontournees

  profiles:
    active: qa

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: tinyllama